EXAMENFINALN00038802/Controllers/AuthController.cs
using EXAMENFINALN00038802.Models;
using EXAMENFINALN00038802.Repository;
using EXAMENFINALN00038802.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace EXAMENFINALN00038802.Controllers
{
    [Authorize]
    public class AuthController : Controller
    {
        private readonly IAuthRepository context;
        private readonly IClaimService claim;

        public AuthController(IAuthRepository context, IClaimService claim)
        {
            this.context = context;
            this.claim = claim;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View("Login");
        }
        [HttpPost]
        public IActionResult Login(string username, string password)
        {
            var user = context.GetUsuario(username, password);

            if (user != null)
            {
                var claims = new List<Claim> {
                    new Claim(ClaimTypes.Name, username)
                };

                var claimsIdentity = new ClaimsIdentity(claims, "Login");
                var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

                claim.SetHttpContext(HttpContext);
                claim.Login(claimsPrincipal);

                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError("Login", "Usuario o contraseña incorrectos.");
            return View("Login");
        }
        [HttpGet]
        public IActionResult Logout()
        {
            claim.SetHttpContext(HttpContext);
            claim.Logout();
            return RedirectToAction("Login");
        }

        [HttpGet]
        public ActionResult Registrar()
        {
            return View("Registrar");
        }

        [HttpPost]
        public ActionResult Registrar(Usuario user, string passwordConf)
        {
            var usuarios = context.GetUsuarios();
            foreach (var item in usuarios)
            {
                if (item.Username == user.Username)
                    ModelState.AddModelError("Username", "Este usuario ya existe");
            }
            if (user.Password != passwordConf)
                ModelState.AddModelError("PasswordConf", "Las contraseñas no coinciden");

            if (ModelState.IsValid)
            {
                context.SaveUsuario(user);
                return RedirectToAction("Login");
            }
            return View("Registrar", user);
        }
    }
}

EXAMENFINALN00038802/Controllers/NotaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EXAMENFINALN00038802.Models;
using EXAMENFINALN00038802.Repository;
using EXAMENFINALN00038802.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EXAMENFINALN00038802.Controllers
{
    [Authorize]
    public class NotaController : Controller
    {
        private readonly IClaimService claim;
        private readonly INotaRepository context;
        public NotaController(INotaRepository context, IClaimService claim)
        {
            this.context = context;
            this.claim = claim;
        }
        [HttpGet]
        public IActionResult Index(string buscar)
        {
            claim.SetHttpContext(HttpContext);
            var notas = context.GetNotas(claim.GetLoggedUser().Id);

            ViewBag.Etiquetas = context.GetEtiquetas();
            ViewBag.Etiquetitas = context.GetEtiquetaNotas();
            var not = context.GetNotas(claim.GetLoggedUser().Id);
            if (!String.IsNullOrEmpty(buscar))
                notas = notas.Where(o => o.Titulo.Contains(buscar) || o.Contenido.Contains(buscar)).ToList();
            return View("Index", notas);
        }

        [HttpGet]
        public IActionResult _Index(string search)
        {
            claim.SetHttpContext(HttpContext);
            var notas = context.GetNotas(claim.GetLoggedUser().Id);
            ViewBag.Etiquetitas = context.GetEtiquetaNotas();
            ViewBag.Etiquetas = context.GetEtiquetas();

            if (!String.IsNullOrEmpty(search))
            {
                notas = notas.Where(o => o.Titulo.Contains(search) || o.Contenido.Contains(search)).ToList();
                return View(notas);
            }
            return View(notas);
        }

        [HttpGet]
        public IActionResult Categoria(int IdCategoria)
        {
            claim.SetHttpContext(HttpContext);
            var categoria = context.GetNotas(claim.GetLoggedUser().Id);

            ViewBag.Etiquetitas = context.GetEtiquetaNotas();
            ViewBag.Etiquetas = context.GetEtiquetas();

            var etiqueta = context.GetCategoriaNotas(claim.GetLoggedUser().Id, IdCategoria);
            return View("Categoria", etiqueta);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Etiquetas = context.GetEtiquetas();
            return View(new Nota());
        }
        [HttpPost]
        public IActionResult Create(Nota nota, List<int> etiqueta)
        {
            List<EtiquetaNota> etic = new List<EtiquetaNota>();

            if (etiqueta.Count() == 0)
                ModelState.AddModelError("etiqueta", "Escoja una opción");

            nota.Fecha = DateTime.Now;
            claim.SetHttpContext(HttpContext);
            nota.IdUser = claim.GetLoggedUser().Id;
            if (ModelState.IsValid)
            {
                context.GuardarNota(nota);
                foreach (var item in etiqueta)
                {
                    var etique = new EtiquetaNota();
                    etique.IdEtiqueta = item;
                    etique.IdNota = nota.Id;
                    etic.Add(etique);
                }
                context.GuardarEtiqueNota(etic);
                return RedirectToAction("Index");
            }
            else
            {
                Response.StatusCode = 400;
                ViewBag.Etiquetas = context.GetEtiquetas();
                return View("Create", new Nota());
            }

        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Etiquetas = context.GetEtiquetas();
            var nota = context.GetNota(id);
            return View(nota);

        }
        [HttpPost]
        public IActionResult Edit(Nota nota, int IdEti, List<int> etiqueta)
        {
            nota.Fecha = DateTime.Now;
            List<EtiquetaNota> etic = new List<EtiquetaNota>();

            if (etiqueta.Count() == 0)
                ModelState.AddModelError("etiqueta", "Seleccione por lo menos una");
            claim.SetHttpContext(HttpContext);
            nota.IdUser = claim.GetLoggedUser().Id;
            if (ModelState.IsValid)
            {
                context.EliminaEtiquetas(IdEti);
                context.ActNota(nota);
                foreach (var item in etiqueta)
                {
                    var etique = new EtiquetaNota();
                    etique.IdEtiqueta = item;
                    etique.IdNota = nota.Id;
                    etic.Add(etique);
                }
                context.GuardarEtiqueNota(etic);
                return RedirectToAction("Index");
            }
            ViewBag.Etiquetas = context.GetEtiquetas();
            return View("Edit", nota);
        }
        [HttpGet]
        public IActionResult Det(int id)
        {
            var etiqueta = context.GetEtiquetas();
            ViewBag.Etiquetas = context.GetEtiquetaNotas();
            var nota = context.GetNota(id);
            return View(nota);
        }
        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            context.EliminaNota(id);
            return RedirectToAction("Index");
        }
    }
}

EXAMENFINALN00038802/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EXAMENFINALN00038802</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EXAMENFINALN00038802</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nota" asp-action="Index">Notas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EXAMENFINALN00038802 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>